-- =====================================================================
-- GESTOR DE ENTREGA · 01_estrutura.sql
-- Rode UMA vez no Supabase: SQL Editor > New query > cole tudo > Run.
-- Cria tabelas, regras de acesso (RLS), funções de login/aprovação
-- e o bucket de anexos. Pode rodar de novo sem perder dados? NÃO:
-- este script é para banco vazio. Para recomeçar do zero, veja o README.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------
-- 1. QUEM VIRA ADMIN AUTOMATICAMENTE NO PRIMEIRO CADASTRO
--    (troque/adicione e-mails aqui antes de rodar, se quiser)
-- ---------------------------------------------------------------------
create table public.admins_iniciais (email text primary key);
insert into public.admins_iniciais(email) values ('rodrigo.machado@rottasconstrutora.com.br');

-- Funções (papéis) que existem no app
create table public.funcoes (
  codigo text primary key,
  nome   text not null,
  ordem  int  not null
);
insert into public.funcoes values
  ('admin','Admin',1),('obra','Obra',2),('instalacoes','Instalações',3),('qualidade','Qualidade',4),
  ('rc','Relacionamento (RC)',5),('financeiro','Financeiro',6),('arquitetura','Arquitetura',7);

-- ---------------------------------------------------------------------
-- 2. PERFIS (1 por pessoa que se cadastra no login)
-- ---------------------------------------------------------------------
create table public.perfis (
  id            uuid primary key references auth.users(id) on delete cascade,
  email         text not null unique,
  login         text not null unique,          -- ex.: rodrigo.machado (igual ao app antigo)
  nome          text not null default '',
  status        text not null default 'pendente' check (status in ('pendente','aprovado','bloqueado')),
  funcoes       text[] not null default '{}',
  pedido_senha  timestamptz,                   -- pessoa clicou em "Esqueci minha senha"
  trocar_senha  boolean not null default false, -- senha provisória: o app obriga a trocar no próximo login
  foto          text,                          -- endereço da foto no Storage (espaço "fotos")
  prefs         jsonb not null default '{}',   -- preferências: tela inicial da obra, tema
  criado_em     timestamptz not null default now(),
  aprovado_em   timestamptz,
  aprovado_por  text
);

-- Permissões do SharePoint (ge_usuarios), usadas só como SUGESTÃO na aprovação
create table public.funcoes_antigas (
  login   text primary key,
  funcoes text[] not null default '{}'
);

-- ---------------------------------------------------------------------
-- 3. DADOS DO APP (mesmos nomes de campo das listas do SharePoint)
-- ---------------------------------------------------------------------
create table public.obras (
  id        bigint generated by default as identity primary key,
  ordem     int     not null default 0,
  nome      text    not null,
  cidade    text    not null default '',
  ativa     boolean not null default true,
  foto_url  text,
  -- antes eram regras fixas por ID de obra no Power Apps (1, 7 e 8)
  config    jsonb   not null default '{"tipo":"predio","testes":["esgoto","aguafria","dreno","gas","eletrico"],"previa":false,"aprovarDireto":false}'
);

-- Quem enxerga cada obra (antes: ge_obras.usuarios "a, b, c")
create table public.obra_acessos (
  obra_id bigint not null references public.obras(id) on delete cascade,
  login   text   not null,
  primary key (obra_id, login)
);
create index on public.obra_acessos(login);

create table public.clientes (
  id         bigint generated by default as identity primary key,
  nome       text not null default '',
  email      text not null default '',
  telefone   text not null default '',            -- só dígitos: 5541999999999
  criado_por text,
  criado_em  timestamptz not null default now()
);

create table public.locais (                         -- ge_obras_locais
  id       bigint generated by default as identity primary key,
  id_obra  bigint not null references public.obras(id) on delete cascade,
  nivel1   text   not null default '',               -- Bloco A / Quadra 1
  niveis2  text   not null default ''                -- "1° Pavimento, 2° Pavimento"
);
create index on public.locais(id_obra);

create table public.horarios (                       -- ge_obras_horarios
  id       bigint generated by default as identity primary key,
  id_obra  bigint not null unique references public.obras(id) on delete cascade,
  segunda  text not null default '[]',
  terca    text not null default '[]',
  quarta   text not null default '[]',
  quinta   text not null default '[]',
  sexta    text not null default '[]',
  sabado   text not null default '[]'
);

create table public.unidades (                       -- ge_unidades
  id                    bigint generated by default as identity primary key,
  id_obra               bigint not null references public.obras(id) on delete cascade,
  nivel_1               bigint references public.locais(id),   -- excluir local com unidades é bloqueado
  nivel_2               int,
  unidade               text not null default '',
  modulo                text not null default '',
  id_cliente            bigint references public.clientes(id) on delete set null,
  sub_etapa             int  not null default 1,
  rep_teste_esgoto      text not null default '',
  rep_teste_aguafria    text not null default '',
  rep_teste_dreno       text not null default '',
  rep_teste_eletrico    text not null default '',
  rep_teste_gas         text not null default '',
  rep_vistoria_at       text not null default '',
  rep_vistoria_previa   text not null default '',
  rep_vistoria_cliente  text not null default '',
  agendamento           text not null default '',   -- '' | Pendente | dd/mm/aaaa HH:MM | Concluído
  financeiro_status     text not null default '',
  financeiro_motivo     text not null default '',
  prioridade            text not null default '',
  atualizado_em         timestamptz not null default now()
);
create index on public.unidades(id_obra);
create index on public.unidades(id_cliente);

create table public.tarefas (                        -- ge_tarefas + histórico do ge_bases_json
  id            bigint generated by default as identity primary key,
  id_obra       bigint not null references public.obras(id) on delete cascade,
  id_unidade    bigint not null,
  acao          text   not null,
  etapa_antiga  int,
  etapa_nova    int,
  obs           text not null default '',
  repeticao     int,
  coluna        text not null default '',
  autor         text not null default '',
  data          timestamptz not null default now(),
  agendamento   text not null default '',
  anexos        jsonb,       -- [{nome,tamanho,path}]  (novo)
  checklist     jsonb,       -- checklist das vistorias (novo)
  assinatura    text         -- assinatura do cliente em PNG base64 (novo)
);
create index on public.tarefas(id_obra);
create index on public.tarefas(id_unidade);

create table public.areas (                          -- ge_areas_comuns
  id                      bigint generated by default as identity primary key,
  id_obra                 bigint not null references public.obras(id) on delete cascade,
  descricao               text not null default '',
  sub_etapa               int  not null default 1,
  rep_vistoria_qualidade  text not null default '',
  rep_vistoria_arq        text not null default '',
  agendamento             text not null default '',
  rep_vistoria_sindico    text not null default '',
  atualizado_em           timestamptz not null default now()
);
create index on public.areas(id_obra);

create table public.tarefas_ac (                     -- ge_tarefas_ac
  id            bigint generated by default as identity primary key,
  id_obra       bigint not null references public.obras(id) on delete cascade,
  id_local      bigint not null,
  acao          text   not null,
  etapa_antiga  int,
  etapa_nova    int,
  obs           text not null default '',
  repeticao     int,
  coluna        text not null default '',
  autor         text not null default '',
  data          timestamptz not null default now(),
  agendamento   text not null default '',
  anexos        jsonb
);
create index on public.tarefas_ac(id_obra);
create index on public.tarefas_ac(id_local);

-- Laudos: cliente trouxe engenheiro na vistoria -> o laudo dele precisa ser enviado (RC cobra)
create table public.laudos (
  id            bigint generated by default as identity primary key,
  id_obra       bigint not null references public.obras(id) on delete cascade,
  id_unidade    bigint not null,
  id_tarefa     bigint,
  engenheiro    text not null default '',
  status        text not null default 'pendente' check (status in ('pendente','recebido')),
  criado_em     timestamptz not null default now(),
  criado_por    text,
  recebido_em   timestamptz,
  recebido_por  text,
  obs           text not null default '',
  anexos        jsonb
);
create index on public.laudos(id_obra);

-- ---------------------------------------------------------------------
-- 4. FUNÇÕES DE APOIO (quem sou eu / o que posso)
-- ---------------------------------------------------------------------
create or replace function public.eu_aprovado() returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from perfis where id = auth.uid() and status = 'aprovado')
$$;

create or replace function public.meu_login() returns text
language sql stable security definer set search_path = public as $$
  select login from perfis where id = auth.uid() and status = 'aprovado'
$$;

-- admin vale como todas as funções nas checagens do servidor
create or replace function public.tenho_funcao(variadic f text[]) returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from perfis where id = auth.uid() and status = 'aprovado'
                and (funcoes && f or 'admin' = any(funcoes)))
$$;

create or replace function public.sou_admin() returns boolean
language sql stable security definer set search_path = public as $$
  select exists(select 1 from perfis where id = auth.uid() and status = 'aprovado' and 'admin' = any(funcoes))
$$;

create or replace function public.acesso_obra(o bigint) returns boolean
language sql stable security definer set search_path = public as $$
  select public.sou_admin() or exists(
    select 1 from obra_acessos a join perfis p on p.login = a.login
    where p.id = auth.uid() and p.status = 'aprovado' and a.obra_id = o)
$$;

-- ---------------------------------------------------------------------
-- 5. CADASTRO NOVO → PERFIL "PENDENTE" (o admin aprova no app)
-- ---------------------------------------------------------------------
create or replace function public.novo_usuario() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_email text := lower(new.email);
  v_login text;
  v_nome  text;
  v_admin boolean;
begin
  v_login := case when v_email like '%@rottasconstrutora.com.br' then split_part(v_email,'@',1) else v_email end;
  if exists(select 1 from perfis where login = v_login) then v_login := v_email; end if;
  v_nome  := nullif(trim(coalesce(new.raw_user_meta_data->>'nome','')),'');
  if v_nome is null then v_nome := initcap(replace(split_part(v_login,'@',1),'.',' ')); end if;
  v_admin := exists(select 1 from admins_iniciais where lower(email) = v_email);

  insert into perfis(id,email,login,nome,status,funcoes,aprovado_em,aprovado_por)
  values (new.id, v_email, v_login, v_nome,
          case when v_admin then 'aprovado' else 'pendente' end,
          case when v_admin then array(select codigo from funcoes order by ordem) else '{}' end,
          case when v_admin then now() end,
          case when v_admin then 'automático' end);
  return new;
end $$;

create trigger ao_criar_usuario after insert on auth.users
for each row execute function public.novo_usuario();

-- Lista de nomes (para mostrar "Fulano aprovou..." no histórico)
create view public.perfis_publicos as
  select login, nome, funcoes, foto from public.perfis where status <> 'pendente' and public.eu_aprovado();

-- ---------------------------------------------------------------------
-- 6. REGRAS DE ACESSO (RLS)
-- ---------------------------------------------------------------------
alter table public.admins_iniciais  enable row level security;
alter table public.funcoes          enable row level security;
alter table public.perfis           enable row level security;
alter table public.funcoes_antigas  enable row level security;
alter table public.obras            enable row level security;
alter table public.obra_acessos     enable row level security;
alter table public.clientes         enable row level security;
alter table public.locais           enable row level security;
alter table public.horarios         enable row level security;
alter table public.unidades         enable row level security;
alter table public.tarefas          enable row level security;
alter table public.areas            enable row level security;
alter table public.tarefas_ac       enable row level security;
alter table public.laudos           enable row level security;

-- ninguém sem login lê nada; tarefas só entram pela função registrar_acao
revoke all on all tables in schema public from anon;
revoke insert, update, delete on public.tarefas, public.tarefas_ac, public.laudos, public.perfis,
  public.funcoes_antigas, public.obra_acessos, public.admins_iniciais, public.funcoes from authenticated;
-- na unidade, a tela só pode mudar estes campos; status/etapa só pela função registrar_acao
revoke update on public.unidades from authenticated;
grant  update (nivel_1, nivel_2, unidade, modulo, id_cliente, prioridade) on public.unidades to authenticated;
revoke update on public.areas from authenticated;
grant  update (descricao) on public.areas to authenticated;
revoke update on public.obras from authenticated;
grant  update (ordem, nome, cidade, ativa, foto_url, config) on public.obras to authenticated;

create policy "ler funcoes"      on public.funcoes for select to authenticated using (true);
create policy "ler meu perfil"   on public.perfis  for select to authenticated using (id = auth.uid() or public.sou_admin());
create policy "admin le antigas" on public.funcoes_antigas for select to authenticated using (public.sou_admin());

create policy "ler obras"     on public.obras for select to authenticated using (public.eu_aprovado());
create policy "admin cria obra"  on public.obras for insert to authenticated with check (public.sou_admin());
create policy "admin muda obra"  on public.obras for update to authenticated using (public.sou_admin()) with check (public.sou_admin());
create policy "admin apaga obra" on public.obras for delete to authenticated using (public.sou_admin());

create policy "ler acessos" on public.obra_acessos for select to authenticated
  using (public.sou_admin() or login = public.meu_login());

create policy "ler clientes"   on public.clientes for select to authenticated using (public.eu_aprovado());
create policy "rc cria cliente"  on public.clientes for insert to authenticated with check (public.tenho_funcao('rc'));
create policy "rc muda cliente"  on public.clientes for update to authenticated using (public.tenho_funcao('rc')) with check (public.tenho_funcao('rc'));
create policy "rc apaga cliente" on public.clientes for delete to authenticated using (public.tenho_funcao('rc'));

create policy "ler locais"    on public.locais for select to authenticated using (public.acesso_obra(id_obra));
create policy "obra cria local"  on public.locais for insert to authenticated with check (public.tenho_funcao('obra') and public.acesso_obra(id_obra));
create policy "obra muda local"  on public.locais for update to authenticated using (public.tenho_funcao('obra') and public.acesso_obra(id_obra)) with check (public.acesso_obra(id_obra));
create policy "obra apaga local" on public.locais for delete to authenticated using (public.tenho_funcao('obra') and public.acesso_obra(id_obra));

create policy "ler horarios"  on public.horarios for select to authenticated using (public.acesso_obra(id_obra));
create policy "cria horarios" on public.horarios for insert to authenticated with check (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra));
create policy "muda horarios" on public.horarios for update to authenticated using (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra)) with check (public.acesso_obra(id_obra));

create policy "ler unidades"    on public.unidades for select to authenticated using (public.acesso_obra(id_obra));
create policy "obra cria unidade"  on public.unidades for insert to authenticated
  with check (public.tenho_funcao('obra') and public.acesso_obra(id_obra) and sub_etapa = 1);
create policy "muda unidade"       on public.unidades for update to authenticated
  using (public.tenho_funcao('obra','rc') and public.acesso_obra(id_obra)) with check (public.acesso_obra(id_obra));
create policy "obra apaga unidade" on public.unidades for delete to authenticated using (public.tenho_funcao('obra') and public.acesso_obra(id_obra));

create policy "ler areas"    on public.areas for select to authenticated using (public.acesso_obra(id_obra));
create policy "obra cria area"  on public.areas for insert to authenticated with check (public.tenho_funcao('obra') and public.acesso_obra(id_obra) and sub_etapa = 1);
create policy "obra muda area"  on public.areas for update to authenticated using (public.tenho_funcao('obra') and public.acesso_obra(id_obra)) with check (public.acesso_obra(id_obra));
create policy "obra apaga area" on public.areas for delete to authenticated using (public.tenho_funcao('obra') and public.acesso_obra(id_obra));

create policy "ler tarefas"    on public.tarefas    for select to authenticated using (public.acesso_obra(id_obra));
create policy "ler tarefas ac" on public.tarefas_ac for select to authenticated using (public.acesso_obra(id_obra));
create policy "ler laudos"     on public.laudos     for select to authenticated using (public.acesso_obra(id_obra));

-- O app carrega o histórico sem a imagem da assinatura (pesada); ela é buscada só quando alguém clica
create view public.tarefas_lista with (security_invoker = true) as
  select id, id_obra, id_unidade, acao, etapa_antiga, etapa_nova, obs, repeticao, coluna, autor, data, agendamento,
         anexos, checklist, (assinatura is not null) as tem_assinatura
  from public.tarefas;
grant select on public.tarefas_lista to authenticated;

-- ---------------------------------------------------------------------
-- 7. AÇÕES DO FLUXO (aprovar, reprovar, agendar...) — sempre por aqui
--    Confere permissão, confere se ninguém mexeu antes (conflito),
--    grava o novo status e registra a tarefa com autor e hora do servidor.
-- ---------------------------------------------------------------------
create or replace function public.pode_acao(p_tipo text, p_acao text, p_coluna text) returns boolean
language plpgsql stable security definer set search_path = public as $$
begin
  if p_tipo = 'unidade' then
    if p_coluna like 'rep_teste_%' then
      return case when p_acao in ('aprovar','reprovar') then tenho_funcao('instalacoes')
                  when p_acao in ('liberar','cancelar','corrigir') then tenho_funcao('obra') else false end;
    elsif p_coluna = '' then
      return p_acao in ('finalizar','aprovarDireto','cancelar') and tenho_funcao('obra');
    elsif p_coluna in ('rep_vistoria_at','rep_vistoria_previa') then
      return case when p_acao in ('aprovar','reprovar') then tenho_funcao('qualidade')
                  when p_acao = 'corrigir' then tenho_funcao('obra') else false end;
    elsif p_coluna = 'agendamento' then
      return p_acao in ('agendar','cancelar') and tenho_funcao('rc');
    elsif p_coluna = 'rep_vistoria_cliente' then
      return case when p_acao in ('aprovar','reprovar') then tenho_funcao('qualidade','obra')
                  when p_acao = 'corrigir' then tenho_funcao('obra') else false end;
    end if;
  elsif p_tipo = 'area' then
    if p_coluna = '' then
      return p_acao in ('liberar','cancelar') and tenho_funcao('obra');
    elsif p_coluna in ('rep_vistoria_qualidade','rep_vistoria_sindico') then
      return case when p_acao in ('aprovar','reprovar') then tenho_funcao('qualidade')
                  when p_acao = 'corrigir' then tenho_funcao('obra') else false end;
    elsif p_coluna = 'rep_vistoria_arq' then
      return case when p_acao in ('aprovar','reprovar') then tenho_funcao('arquitetura')
                  when p_acao = 'corrigir' then tenho_funcao('obra') else false end;
    elsif p_coluna = 'agendamento' then
      return p_acao in ('agendar','cancelar') and tenho_funcao('rc');
    end if;
  end if;
  return false;
end $$;

create or replace function public.registrar_acao(
  p_tipo text,        -- 'unidade' | 'area'
  p_id bigint,        -- id da unidade ou da área
  p_acao text,
  p_coluna text,
  p_antes jsonb,      -- valores que a tela viu antes (para detectar conflito)
  p_depois jsonb,     -- novos valores de status/etapa
  p_tarefa jsonb      -- {id, etapa_antiga, etapa_nova, obs, repeticao, agendamento, anexos, checklist, assinatura}
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_login text := meu_login();
  v_atual jsonb;
  v_obra  bigint;
  k text;
  v_permitidas text[];
  v_novo jsonb;
  v_tar jsonb;
  v_laudo jsonb;
  v_quando timestamptz;
begin
  if v_login is null then raise exception 'sem_acesso: usuário não aprovado'; end if;
  if not pode_acao(p_tipo, p_acao, coalesce(p_coluna,'')) then
    raise exception 'sem_permissao: você não tem a função necessária para esta ação';
  end if;

  if p_tipo = 'unidade' then
    select to_jsonb(u), u.id_obra into v_atual, v_obra from unidades u where u.id = p_id for update;
    v_permitidas := array['sub_etapa','rep_teste_esgoto','rep_teste_aguafria','rep_teste_dreno','rep_teste_eletrico','rep_teste_gas',
                          'rep_vistoria_at','rep_vistoria_previa','rep_vistoria_cliente','agendamento'];
  elsif p_tipo = 'area' then
    select to_jsonb(a), a.id_obra into v_atual, v_obra from areas a where a.id = p_id for update;
    v_permitidas := array['sub_etapa','rep_vistoria_qualidade','rep_vistoria_arq','agendamento','rep_vistoria_sindico'];
  else
    raise exception 'tipo inválido';
  end if;
  if v_atual is null then raise exception 'nao_encontrado: registro não existe mais'; end if;

  -- agendamento com o cliente: pelo menos 24 h de antecedência (admin pode registrar fora disso)
  if p_tipo = 'unidade' and coalesce(p_coluna,'') = 'agendamento' and p_acao = 'agendar' and not sou_admin() then
    begin
      v_quando := (to_timestamp(p_depois->>'agendamento', 'DD/MM/YYYY HH24:MI')::timestamp) at time zone 'America/Sao_Paulo';
    exception when others then raise exception 'data do agendamento inválida';
    end;
    if v_quando < now() + interval '24 hours' then
      raise exception 'antecedencia: o agendamento precisa ter pelo menos 24 horas de antecedência';
    end if;
  end if;
  if not acesso_obra(v_obra) then raise exception 'sem_acesso: você não tem acesso a esta obra'; end if;

  -- conflito: alguém mudou depois que a tela carregou
  for k in select jsonb_object_keys(coalesce(p_antes,'{}')) loop
    if coalesce(v_atual->>k,'') is distinct from coalesce(p_antes->>k,'') then
      raise exception 'conflito: % mudou de "%" para "%"', k, p_antes->>k, v_atual->>k;
    end if;
  end loop;
  for k in select jsonb_object_keys(coalesce(p_depois,'{}')) loop
    if not k = any(v_permitidas) then raise exception 'campo não permitido: %', k; end if;
  end loop;

  if p_tipo = 'unidade' then
    update unidades u set
      sub_etapa            = coalesce((p_depois->>'sub_etapa')::int, u.sub_etapa),
      rep_teste_esgoto     = coalesce(p_depois->>'rep_teste_esgoto',     u.rep_teste_esgoto),
      rep_teste_aguafria   = coalesce(p_depois->>'rep_teste_aguafria',   u.rep_teste_aguafria),
      rep_teste_dreno      = coalesce(p_depois->>'rep_teste_dreno',      u.rep_teste_dreno),
      rep_teste_eletrico   = coalesce(p_depois->>'rep_teste_eletrico',   u.rep_teste_eletrico),
      rep_teste_gas        = coalesce(p_depois->>'rep_teste_gas',        u.rep_teste_gas),
      rep_vistoria_at      = coalesce(p_depois->>'rep_vistoria_at',      u.rep_vistoria_at),
      rep_vistoria_previa  = coalesce(p_depois->>'rep_vistoria_previa',  u.rep_vistoria_previa),
      rep_vistoria_cliente = coalesce(p_depois->>'rep_vistoria_cliente', u.rep_vistoria_cliente),
      agendamento          = coalesce(p_depois->>'agendamento',          u.agendamento),
      atualizado_em        = now()
    where u.id = p_id returning to_jsonb(u) into v_novo;

    insert into tarefas(id,id_obra,id_unidade,acao,etapa_antiga,etapa_nova,obs,repeticao,coluna,autor,data,agendamento,anexos,checklist,assinatura)
    values (coalesce((p_tarefa->>'id')::bigint, nextval(pg_get_serial_sequence('public.tarefas','id'))),
            v_obra, p_id, case when p_acao = 'aprovarDireto' then 'finalizar' else p_acao end,
            (p_tarefa->>'etapa_antiga')::int, (p_tarefa->>'etapa_nova')::int,
            coalesce(p_tarefa->>'obs',''), (p_tarefa->>'repeticao')::int, coalesce(p_coluna,''),
            v_login, now(), coalesce(p_tarefa->>'agendamento',''),
            p_tarefa->'anexos', p_tarefa->'checklist', p_tarefa->>'assinatura')
    returning to_jsonb(tarefas.*) into v_tar;

    -- cliente veio com engenheiro: fica um laudo pendente de envio
    if p_coluna = 'rep_vistoria_cliente' and p_acao in ('aprovar','reprovar') and p_tarefa ? 'laudo' and jsonb_typeof(p_tarefa->'laudo') = 'object' then
      insert into laudos(id_obra, id_unidade, id_tarefa, engenheiro, criado_por)
      values (v_obra, p_id, (v_tar->>'id')::bigint, left(coalesce(p_tarefa->'laudo'->>'engenheiro',''),120), v_login)
      returning to_jsonb(laudos.*) into v_laudo;
    end if;
  else
    update areas a set
      sub_etapa              = coalesce((p_depois->>'sub_etapa')::int, a.sub_etapa),
      rep_vistoria_qualidade = coalesce(p_depois->>'rep_vistoria_qualidade', a.rep_vistoria_qualidade),
      rep_vistoria_arq       = coalesce(p_depois->>'rep_vistoria_arq',       a.rep_vistoria_arq),
      agendamento            = coalesce(p_depois->>'agendamento',            a.agendamento),
      rep_vistoria_sindico   = coalesce(p_depois->>'rep_vistoria_sindico',   a.rep_vistoria_sindico),
      atualizado_em          = now()
    where a.id = p_id returning to_jsonb(a) into v_novo;

    insert into tarefas_ac(id,id_obra,id_local,acao,etapa_antiga,etapa_nova,obs,repeticao,coluna,autor,data,agendamento,anexos)
    values (coalesce((p_tarefa->>'id')::bigint, nextval(pg_get_serial_sequence('public.tarefas_ac','id'))),
            v_obra, p_id, p_acao, (p_tarefa->>'etapa_antiga')::int, (p_tarefa->>'etapa_nova')::int,
            coalesce(p_tarefa->>'obs',''), (p_tarefa->>'repeticao')::int, coalesce(p_coluna,''),
            v_login, now(), coalesce(p_tarefa->>'agendamento',''), p_tarefa->'anexos')
    returning to_jsonb(tarefas_ac.*) into v_tar;
  end if;

  return jsonb_build_object('linha', v_novo, 'tarefa', v_tar, 'laudo', v_laudo);
end $$;

-- Reserva IDs para registros criados na tela (unidade, cliente, local...)
create or replace function public.reservar_ids(p_tabela text, p_n int default 20) returns bigint[]
language plpgsql security definer set search_path = public as $$
begin
  if not eu_aprovado() then raise exception 'sem_acesso'; end if;
  if p_tabela not in ('clientes','locais','horarios','unidades','areas','tarefas','tarefas_ac') then raise exception 'tabela inválida'; end if;
  return array(select nextval(pg_get_serial_sequence('public.'||p_tabela,'id')) from generate_series(1, least(greatest(p_n,1),200)));
end $$;

-- ---------------------------------------------------------------------
-- 8. ADMINISTRAÇÃO DE USUÁRIOS (tela "Usuários" do app)
-- ---------------------------------------------------------------------
create or replace function public.admin_aprovar(p_id uuid, p_funcoes text[], p_obras bigint[]) returns void
language plpgsql security definer set search_path = public as $$
declare v_login text;
begin
  if not sou_admin() then raise exception 'sem_permissao'; end if;
  if exists(select 1 from unnest(p_funcoes) f where f not in (select codigo from funcoes)) then
    raise exception 'função inválida';
  end if;
  if coalesce(array_length(p_funcoes,1),0) = 0 then raise exception 'escolha pelo menos uma função'; end if;
  if 'admin' = any(p_funcoes) and not exists(select 1 from perfis p join admins_iniciais a on lower(a.email) = p.email where p.id = p_id) then
    raise exception 'a função Admin é exclusiva (só e-mails da lista admins_iniciais)';
  end if;
  update perfis set status = 'aprovado', funcoes = p_funcoes,
         aprovado_em = coalesce(aprovado_em, now()), aprovado_por = coalesce(aprovado_por, meu_login())
   where id = p_id returning login into v_login;
  if v_login is null then raise exception 'perfil não encontrado'; end if;
  delete from obra_acessos where login = v_login;
  insert into obra_acessos(obra_id, login) select distinct o, v_login from unnest(coalesce(p_obras,'{}')) o
    where exists(select 1 from obras where id = o);
end $$;

create or replace function public.admin_status(p_id uuid, p_status text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if not sou_admin() then raise exception 'sem_permissao'; end if;
  if p_id = auth.uid() then raise exception 'você não pode mudar o seu próprio acesso'; end if;
  if p_status not in ('pendente','aprovado','bloqueado') then raise exception 'status inválido'; end if;
  update perfis set status = p_status where id = p_id;
end $$;

create or replace function public.admin_redefinir_senha(p_id uuid, p_senha text) returns void
language plpgsql security definer set search_path = public, extensions as $$
begin
  if not sou_admin() then raise exception 'sem_permissao'; end if;
  if length(coalesce(p_senha,'')) < 6 then raise exception 'a senha precisa ter pelo menos 6 caracteres'; end if;
  update auth.users set encrypted_password = extensions.crypt(p_senha, extensions.gen_salt('bf')), updated_at = now()
   where id = p_id;
  update perfis set pedido_senha = null, trocar_senha = true where id = p_id;
end $$;

-- a pessoa trocou a senha provisória pela dela
create or replace function public.senha_trocada() returns void
language sql security definer set search_path = public as $$
  update perfis set trocar_senha = false where id = auth.uid();
$$;

-- "Esqueci minha senha": só avisa o admin (não diz se o e-mail existe)
create or replace function public.pedir_nova_senha(p_email text) returns void
language sql security definer set search_path = public as $$
  update perfis set pedido_senha = now() where email = lower(trim(p_email));
$$;

-- quem pode chamar cada função
revoke execute on all functions in schema public from public, anon;
grant execute on function public.eu_aprovado(), public.meu_login(), public.tenho_funcao(text[]), public.sou_admin(),
  public.acesso_obra(bigint), public.pode_acao(text,text,text),
  public.registrar_acao(text,bigint,text,text,jsonb,jsonb,jsonb), public.reservar_ids(text,int),
  public.admin_aprovar(uuid,text[],bigint[]), public.admin_status(uuid,text), public.admin_redefinir_senha(uuid,text),
  public.senha_trocada() to authenticated;
grant execute on function public.pedir_nova_senha(text) to anon, authenticated;
grant select on public.perfis_publicos to authenticated;

-- ---------------------------------------------------------------------
-- 9. ANEXOS (fotos/PDF na aprovação do teste de gás)
--    caminho do arquivo: <id_obra>/<id_unidade>/<arquivo>
-- ---------------------------------------------------------------------
insert into storage.buckets(id, name, public) values ('anexos','anexos', false)
on conflict (id) do nothing;

create policy "anexos ler" on storage.objects for select to authenticated
  using (bucket_id = 'anexos' and public.acesso_obra(((storage.foldername(name))[1])::bigint));
create policy "anexos enviar" on storage.objects for insert to authenticated
  with check (bucket_id = 'anexos' and public.acesso_obra(((storage.foldername(name))[1])::bigint));

-- ---------------------------------------------------------------------
-- 10. FOTOS (usuários e capas das obras) e PREFERÊNCIAS — desde a v2.1.2
-- ---------------------------------------------------------------------
create or replace function public.salvar_prefs(p jsonb) returns void
language sql security definer set search_path = public as $$
  update perfis set prefs = coalesce(prefs,'{}') || coalesce(p,'{}') where id = auth.uid();
$$;
create or replace function public.salvar_foto(p_url text) returns void
language plpgsql security definer set search_path = public as $$
begin
  if p_url is not null and (p_url not like 'https://%' or length(p_url) > 600) then raise exception 'endereço de foto inválido'; end if;
  update perfis set foto = p_url where id = auth.uid();
end $$;
revoke execute on function public.salvar_prefs(jsonb), public.salvar_foto(text) from public, anon;
grant execute on function public.salvar_prefs(jsonb), public.salvar_foto(text) to authenticated;

insert into storage.buckets(id, name, public) values ('fotos','fotos', true) on conflict (id) do update set public = true;
create policy "fotos obras admin" on storage.objects for insert to authenticated
  with check (bucket_id = 'fotos' and (storage.foldername(name))[1] = 'obras' and public.sou_admin());
create policy "fotos do proprio perfil" on storage.objects for insert to authenticated
  with check (bucket_id = 'fotos' and (storage.foldername(name))[1] = 'perfis'
              and (storage.foldername(name))[2] = auth.uid()::text and public.eu_aprovado());

-- ---------------------------------------------------------------------
-- 11. LAUDOS — desde a v2.1.4
-- ---------------------------------------------------------------------
create or replace function public.laudo_recebido(p_id bigint, p_obs text, p_anexos jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare v jsonb; v_obra bigint;
begin
  select id_obra into v_obra from laudos where id = p_id;
  if v_obra is null then raise exception 'laudo não encontrado'; end if;
  if not (tenho_funcao('rc') and acesso_obra(v_obra)) then raise exception 'sem_permissao'; end if;
  update laudos set status = 'recebido', recebido_em = now(), recebido_por = meu_login(),
         obs = left(coalesce(p_obs,''),1000), anexos = p_anexos
   where id = p_id returning to_jsonb(laudos.*) into v;
  return v;
end $$;
revoke execute on function public.laudo_recebido(bigint,text,jsonb) from public, anon;
grant execute on function public.laudo_recebido(bigint,text,jsonb) to authenticated;

-- ---------------------------------------------------------------------
-- 12. CLIENTES POR OBRA, LÍDER E EXCEÇÕES DE HORÁRIO — desde a v2.1.5
-- ---------------------------------------------------------------------

-- 1) FUNÇÃO LÍDER --------------------------------------------------------
insert into public.funcoes values ('lider','Líder de área',2) on conflict (codigo) do update set nome = 'Líder de área';

-- 2) CLIENTES POR OBRA ---------------------------------------------------
alter table public.clientes add column if not exists id_obra bigint references public.obras(id) on delete cascade;
create index if not exists clientes_id_obra_idx on public.clientes(id_obra);

update public.clientes c set id_obra = x.o
  from (select id_cliente, min(id_obra) as o from public.unidades where id_cliente is not null group by id_cliente) x
 where x.id_cliente = c.id and c.id_obra is null;

do $$
declare r record; v bigint; n int := 0;
begin
  for r in select u.id_cliente, u.id_obra from public.unidades u join public.clientes c on c.id = u.id_cliente
            where c.id_obra is not null and u.id_obra <> c.id_obra group by 1, 2 loop
    insert into public.clientes(id_obra, nome, email, telefone, criado_por, criado_em)
      select r.id_obra, nome, email, telefone, criado_por, criado_em from public.clientes where id = r.id_cliente
      returning id into v;
    update public.unidades set id_cliente = v where id_cliente = r.id_cliente and id_obra = r.id_obra;
    n := n + 1;
  end loop;
  raise notice '% cópia(s) de cliente criada(s) para obras extras', n;
end $$;

drop policy if exists "ler clientes"     on public.clientes;
drop policy if exists "rc cria cliente"  on public.clientes;
drop policy if exists "rc muda cliente"  on public.clientes;
drop policy if exists "rc apaga cliente" on public.clientes;
drop policy if exists "clientes ler"     on public.clientes;
drop policy if exists "clientes criar"   on public.clientes;
drop policy if exists "clientes mudar"   on public.clientes;
drop policy if exists "clientes apagar"  on public.clientes;
create policy "clientes ler" on public.clientes for select to authenticated
  using (public.eu_aprovado() and (id_obra is null or public.acesso_obra(id_obra)));
create policy "clientes criar" on public.clientes for insert to authenticated
  with check (public.tenho_funcao('rc') and public.tenho_funcao('lider') and id_obra is not null and public.acesso_obra(id_obra));
create policy "clientes mudar" on public.clientes for update to authenticated
  using (public.tenho_funcao('rc') and public.tenho_funcao('lider') and (id_obra is null or public.acesso_obra(id_obra)))
  with check (id_obra is not null and public.acesso_obra(id_obra));
create policy "clientes apagar" on public.clientes for delete to authenticated
  using (public.tenho_funcao('rc') and public.tenho_funcao('lider') and (id_obra is null or public.acesso_obra(id_obra)));

-- 3) HORÁRIOS ------------------------------------------------------------
alter table public.horarios add column if not exists valido_desde date;
alter table public.horarios drop constraint if exists horarios_id_obra_key;
create unique index if not exists horarios_obra_desde_idx on public.horarios(id_obra, coalesce(valido_desde, date '1900-01-01'));
drop policy if exists "apaga horarios" on public.horarios;
create policy "apaga horarios" on public.horarios for delete to authenticated
  using (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra) and valido_desde is not null);

create table if not exists public.horarios_excecoes (
  id        bigint generated by default as identity primary key,
  id_obra   bigint not null references public.obras(id) on delete cascade,
  data      date   not null,
  fechado   boolean not null default true,     -- true = sem vistorias (feriado)
  horarios  text   not null default '[]',      -- se não fechado: [{ID,Horas,Pessoas}]
  motivo    text   not null default '',
  unique (id_obra, data)
);
alter table public.horarios_excecoes enable row level security;
revoke all on public.horarios_excecoes from anon;
drop policy if exists "excecoes ler"    on public.horarios_excecoes;
drop policy if exists "excecoes criar"  on public.horarios_excecoes;
drop policy if exists "excecoes mudar"  on public.horarios_excecoes;
drop policy if exists "excecoes apagar" on public.horarios_excecoes;
create policy "excecoes ler"    on public.horarios_excecoes for select to authenticated using (public.acesso_obra(id_obra));
create policy "excecoes criar"  on public.horarios_excecoes for insert to authenticated with check (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra));
create policy "excecoes mudar"  on public.horarios_excecoes for update to authenticated using (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra)) with check (public.acesso_obra(id_obra));
create policy "excecoes apagar" on public.horarios_excecoes for delete to authenticated using (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra));

create or replace function public.reservar_ids(p_tabela text, p_n int default 20) returns bigint[]
language plpgsql security definer set search_path = public as $$
begin
  if not eu_aprovado() then raise exception 'sem_acesso'; end if;
  if p_tabela not in ('clientes','locais','horarios','horarios_excecoes','unidades','areas','tarefas','tarefas_ac') then raise exception 'tabela inválida'; end if;
  return array(select nextval(pg_get_serial_sequence('public.'||p_tabela,'id')) from generate_series(1, least(greatest(p_n,1),200)));
end $$;
