-- =====================================================================
-- GESTOR DE ENTREGA · 06_atualizacao_2.1.4.sql
-- Rode UMA vez no SQL Editor (pode repetir), depois da 05.
--  1) Laudos: quando o cliente vem com engenheiro na vistoria, fica um laudo
--     pendente de envio (o RC marca quando receber).
--  2) Agendamento com o cliente só com 24 horas de antecedência (admin livre).
-- =====================================================================
create table if not exists public.laudos (
  id            bigint generated by default as identity primary key,
  id_obra       bigint not null references public.obras(id) on delete cascade,
  id_unidade    bigint not null,
  id_tarefa     bigint,
  engenheiro    text not null default '',
  status        text not null default 'pendente' check (status in ('pendente','recebido')),
  criado_em     timestamptz not null default now(),
  criado_por    text,
  recebido_em   timestamptz,
  recebido_por  text,
  obs           text not null default '',
  anexos        jsonb
);
create index if not exists laudos_id_obra_idx on public.laudos(id_obra);
alter table public.laudos enable row level security;
revoke all on public.laudos from anon;
revoke insert, update, delete on public.laudos from authenticated;
drop policy if exists "ler laudos" on public.laudos;
create policy "ler laudos" on public.laudos for select to authenticated using (public.acesso_obra(id_obra));

create or replace function public.registrar_acao(
  p_tipo text,        -- 'unidade' | 'area'
  p_id bigint,        -- id da unidade ou da área
  p_acao text,
  p_coluna text,
  p_antes jsonb,      -- valores que a tela viu antes (para detectar conflito)
  p_depois jsonb,     -- novos valores de status/etapa
  p_tarefa jsonb      -- {id, etapa_antiga, etapa_nova, obs, repeticao, agendamento, anexos, checklist, assinatura}
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_login text := meu_login();
  v_atual jsonb;
  v_obra  bigint;
  k text;
  v_permitidas text[];
  v_novo jsonb;
  v_tar jsonb;
  v_laudo jsonb;
  v_quando timestamptz;
begin
  if v_login is null then raise exception 'sem_acesso: usuário não aprovado'; end if;
  if not pode_acao(p_tipo, p_acao, coalesce(p_coluna,'')) then
    raise exception 'sem_permissao: você não tem a função necessária para esta ação';
  end if;

  if p_tipo = 'unidade' then
    select to_jsonb(u), u.id_obra into v_atual, v_obra from unidades u where u.id = p_id for update;
    v_permitidas := array['sub_etapa','rep_teste_esgoto','rep_teste_aguafria','rep_teste_dreno','rep_teste_eletrico','rep_teste_gas',
                          'rep_vistoria_at','rep_vistoria_previa','rep_vistoria_cliente','agendamento'];
  elsif p_tipo = 'area' then
    select to_jsonb(a), a.id_obra into v_atual, v_obra from areas a where a.id = p_id for update;
    v_permitidas := array['sub_etapa','rep_vistoria_qualidade','rep_vistoria_arq','agendamento','rep_vistoria_sindico'];
  else
    raise exception 'tipo inválido';
  end if;
  if v_atual is null then raise exception 'nao_encontrado: registro não existe mais'; end if;

  -- agendamento com o cliente: pelo menos 24 h de antecedência (admin pode registrar fora disso)
  if p_tipo = 'unidade' and coalesce(p_coluna,'') = 'agendamento' and p_acao = 'agendar' and not sou_admin() then
    begin
      v_quando := (to_timestamp(p_depois->>'agendamento', 'DD/MM/YYYY HH24:MI')::timestamp) at time zone 'America/Sao_Paulo';
    exception when others then raise exception 'data do agendamento inválida';
    end;
    if v_quando < now() + interval '24 hours' then
      raise exception 'antecedencia: o agendamento precisa ter pelo menos 24 horas de antecedência';
    end if;
  end if;
  if not acesso_obra(v_obra) then raise exception 'sem_acesso: você não tem acesso a esta obra'; end if;

  -- conflito: alguém mudou depois que a tela carregou
  for k in select jsonb_object_keys(coalesce(p_antes,'{}')) loop
    if coalesce(v_atual->>k,'') is distinct from coalesce(p_antes->>k,'') then
      raise exception 'conflito: % mudou de "%" para "%"', k, p_antes->>k, v_atual->>k;
    end if;
  end loop;
  for k in select jsonb_object_keys(coalesce(p_depois,'{}')) loop
    if not k = any(v_permitidas) then raise exception 'campo não permitido: %', k; end if;
  end loop;

  if p_tipo = 'unidade' then
    update unidades u set
      sub_etapa            = coalesce((p_depois->>'sub_etapa')::int, u.sub_etapa),
      rep_teste_esgoto     = coalesce(p_depois->>'rep_teste_esgoto',     u.rep_teste_esgoto),
      rep_teste_aguafria   = coalesce(p_depois->>'rep_teste_aguafria',   u.rep_teste_aguafria),
      rep_teste_dreno      = coalesce(p_depois->>'rep_teste_dreno',      u.rep_teste_dreno),
      rep_teste_eletrico   = coalesce(p_depois->>'rep_teste_eletrico',   u.rep_teste_eletrico),
      rep_teste_gas        = coalesce(p_depois->>'rep_teste_gas',        u.rep_teste_gas),
      rep_vistoria_at      = coalesce(p_depois->>'rep_vistoria_at',      u.rep_vistoria_at),
      rep_vistoria_previa  = coalesce(p_depois->>'rep_vistoria_previa',  u.rep_vistoria_previa),
      rep_vistoria_cliente = coalesce(p_depois->>'rep_vistoria_cliente', u.rep_vistoria_cliente),
      agendamento          = coalesce(p_depois->>'agendamento',          u.agendamento),
      atualizado_em        = now()
    where u.id = p_id returning to_jsonb(u) into v_novo;

    insert into tarefas(id,id_obra,id_unidade,acao,etapa_antiga,etapa_nova,obs,repeticao,coluna,autor,data,agendamento,anexos,checklist,assinatura)
    values (coalesce((p_tarefa->>'id')::bigint, nextval(pg_get_serial_sequence('public.tarefas','id'))),
            v_obra, p_id, case when p_acao = 'aprovarDireto' then 'finalizar' else p_acao end,
            (p_tarefa->>'etapa_antiga')::int, (p_tarefa->>'etapa_nova')::int,
            coalesce(p_tarefa->>'obs',''), (p_tarefa->>'repeticao')::int, coalesce(p_coluna,''),
            v_login, now(), coalesce(p_tarefa->>'agendamento',''),
            p_tarefa->'anexos', p_tarefa->'checklist', p_tarefa->>'assinatura')
    returning to_jsonb(tarefas.*) into v_tar;

    -- cliente veio com engenheiro: fica um laudo pendente de envio
    if p_coluna = 'rep_vistoria_cliente' and p_acao in ('aprovar','reprovar') and p_tarefa ? 'laudo' and jsonb_typeof(p_tarefa->'laudo') = 'object' then
      insert into laudos(id_obra, id_unidade, id_tarefa, engenheiro, criado_por)
      values (v_obra, p_id, (v_tar->>'id')::bigint, left(coalesce(p_tarefa->'laudo'->>'engenheiro',''),120), v_login)
      returning to_jsonb(laudos.*) into v_laudo;
    end if;
  else
    update areas a set
      sub_etapa              = coalesce((p_depois->>'sub_etapa')::int, a.sub_etapa),
      rep_vistoria_qualidade = coalesce(p_depois->>'rep_vistoria_qualidade', a.rep_vistoria_qualidade),
      rep_vistoria_arq       = coalesce(p_depois->>'rep_vistoria_arq',       a.rep_vistoria_arq),
      agendamento            = coalesce(p_depois->>'agendamento',            a.agendamento),
      rep_vistoria_sindico   = coalesce(p_depois->>'rep_vistoria_sindico',   a.rep_vistoria_sindico),
      atualizado_em          = now()
    where a.id = p_id returning to_jsonb(a) into v_novo;

    insert into tarefas_ac(id,id_obra,id_local,acao,etapa_antiga,etapa_nova,obs,repeticao,coluna,autor,data,agendamento,anexos)
    values (coalesce((p_tarefa->>'id')::bigint, nextval(pg_get_serial_sequence('public.tarefas_ac','id'))),
            v_obra, p_id, p_acao, (p_tarefa->>'etapa_antiga')::int, (p_tarefa->>'etapa_nova')::int,
            coalesce(p_tarefa->>'obs',''), (p_tarefa->>'repeticao')::int, coalesce(p_coluna,''),
            v_login, now(), coalesce(p_tarefa->>'agendamento',''), p_tarefa->'anexos')
    returning to_jsonb(tarefas_ac.*) into v_tar;
  end if;

  return jsonb_build_object('linha', v_novo, 'tarefa', v_tar, 'laudo', v_laudo);
end $$;

create or replace function public.laudo_recebido(p_id bigint, p_obs text, p_anexos jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare v jsonb; v_obra bigint;
begin
  select id_obra into v_obra from laudos where id = p_id;
  if v_obra is null then raise exception 'laudo não encontrado'; end if;
  if not (tenho_funcao('rc') and acesso_obra(v_obra)) then raise exception 'sem_permissao'; end if;
  update laudos set status = 'recebido', recebido_em = now(), recebido_por = meu_login(),
         obs = left(coalesce(p_obs,''),1000), anexos = p_anexos
   where id = p_id returning to_jsonb(laudos.*) into v;
  return v;
end $$;
revoke execute on function public.laudo_recebido(bigint,text,jsonb) from public, anon;
grant execute on function public.laudo_recebido(bigint,text,jsonb) to authenticated;
