-- =====================================================================
-- GESTOR DE ENTREGA · 07_atualizacao_2.1.5.sql
-- Rode UMA vez no SQL Editor (pode repetir), depois da 06.
--  1) Função "Líder de área" (lider).
--  2) Clientes por obra: cada cliente passa a pertencer a uma obra.
--     - cliente vinculado a unidades de uma obra só: fica nessa obra;
--     - cliente vinculado em mais de uma obra: ganha uma cópia para cada obra
--       extra, e as unidades dessa obra passam a apontar para a cópia;
--     - cliente sem nenhuma unidade: fica "sem obra" e aparece em todas
--       até ser vinculado (aí passa a ser da obra da unidade).
--     Cadastro de clientes: admin, ou quem é RC e também Líder de área.
--  3) Horários: semanas programadas por data ("válido desde") e exceções
--     por dia (feriados ou horários diferentes).
-- =====================================================================

-- 1) FUNÇÃO LÍDER --------------------------------------------------------
insert into public.funcoes values ('lider','Líder de área',2) on conflict (codigo) do update set nome = 'Líder de área';

-- 2) CLIENTES POR OBRA ---------------------------------------------------
alter table public.clientes add column if not exists id_obra bigint references public.obras(id) on delete cascade;
create index if not exists clientes_id_obra_idx on public.clientes(id_obra);

update public.clientes c set id_obra = x.o
  from (select id_cliente, min(id_obra) as o from public.unidades where id_cliente is not null group by id_cliente) x
 where x.id_cliente = c.id and c.id_obra is null;

do $$
declare r record; v bigint; n int := 0;
begin
  for r in select u.id_cliente, u.id_obra from public.unidades u join public.clientes c on c.id = u.id_cliente
            where c.id_obra is not null and u.id_obra <> c.id_obra group by 1, 2 loop
    insert into public.clientes(id_obra, nome, email, telefone, criado_por, criado_em)
      select r.id_obra, nome, email, telefone, criado_por, criado_em from public.clientes where id = r.id_cliente
      returning id into v;
    update public.unidades set id_cliente = v where id_cliente = r.id_cliente and id_obra = r.id_obra;
    n := n + 1;
  end loop;
  raise notice '% cópia(s) de cliente criada(s) para obras extras', n;
end $$;

drop policy if exists "ler clientes"     on public.clientes;
drop policy if exists "rc cria cliente"  on public.clientes;
drop policy if exists "rc muda cliente"  on public.clientes;
drop policy if exists "rc apaga cliente" on public.clientes;
drop policy if exists "clientes ler"     on public.clientes;
drop policy if exists "clientes criar"   on public.clientes;
drop policy if exists "clientes mudar"   on public.clientes;
drop policy if exists "clientes apagar"  on public.clientes;
create policy "clientes ler" on public.clientes for select to authenticated
  using (public.eu_aprovado() and (id_obra is null or public.acesso_obra(id_obra)));
create policy "clientes criar" on public.clientes for insert to authenticated
  with check (public.tenho_funcao('rc') and public.tenho_funcao('lider') and id_obra is not null and public.acesso_obra(id_obra));
create policy "clientes mudar" on public.clientes for update to authenticated
  using (public.tenho_funcao('rc') and public.tenho_funcao('lider') and (id_obra is null or public.acesso_obra(id_obra)))
  with check (id_obra is not null and public.acesso_obra(id_obra));
create policy "clientes apagar" on public.clientes for delete to authenticated
  using (public.tenho_funcao('rc') and public.tenho_funcao('lider') and (id_obra is null or public.acesso_obra(id_obra)));

-- 3) HORÁRIOS ------------------------------------------------------------
alter table public.horarios add column if not exists valido_desde date;
alter table public.horarios drop constraint if exists horarios_id_obra_key;
create unique index if not exists horarios_obra_desde_idx on public.horarios(id_obra, coalesce(valido_desde, date '1900-01-01'));
drop policy if exists "apaga horarios" on public.horarios;
create policy "apaga horarios" on public.horarios for delete to authenticated
  using (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra) and valido_desde is not null);

create table if not exists public.horarios_excecoes (
  id        bigint generated by default as identity primary key,
  id_obra   bigint not null references public.obras(id) on delete cascade,
  data      date   not null,
  fechado   boolean not null default true,     -- true = sem vistorias (feriado)
  horarios  text   not null default '[]',      -- se não fechado: [{ID,Horas,Pessoas}]
  motivo    text   not null default '',
  unique (id_obra, data)
);
alter table public.horarios_excecoes enable row level security;
revoke all on public.horarios_excecoes from anon;
drop policy if exists "excecoes ler"    on public.horarios_excecoes;
drop policy if exists "excecoes criar"  on public.horarios_excecoes;
drop policy if exists "excecoes mudar"  on public.horarios_excecoes;
drop policy if exists "excecoes apagar" on public.horarios_excecoes;
create policy "excecoes ler"    on public.horarios_excecoes for select to authenticated using (public.acesso_obra(id_obra));
create policy "excecoes criar"  on public.horarios_excecoes for insert to authenticated with check (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra));
create policy "excecoes mudar"  on public.horarios_excecoes for update to authenticated using (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra)) with check (public.acesso_obra(id_obra));
create policy "excecoes apagar" on public.horarios_excecoes for delete to authenticated using (public.tenho_funcao('obra','qualidade') and public.acesso_obra(id_obra));

create or replace function public.reservar_ids(p_tabela text, p_n int default 20) returns bigint[]
language plpgsql security definer set search_path = public as $$
begin
  if not eu_aprovado() then raise exception 'sem_acesso'; end if;
  if p_tabela not in ('clientes','locais','horarios','horarios_excecoes','unidades','areas','tarefas','tarefas_ac') then raise exception 'tabela inválida'; end if;
  return array(select nextval(pg_get_serial_sequence('public.'||p_tabela,'id')) from generate_series(1, least(greatest(p_n,1),200)));
end $$;
